# cobol_rust.py — COBOL to Rust translator
# The tern dives deep into COBOL and emerges with Rust

import re

class COBOLToRust:
    """Translate COBOL business logic to production-grade Rust"""
    
    def __init__(self):
        self.rust_types = {
            '9(10)': 'u64',
            '9(8)': 'u32',
            'V99': 'f64',
        }
    
    def translate_data_division(self, data_lines):
        """Translate COBOL DATA DIVISION to Rust struct fields"""
        rust_fields = []
        
        for line in data_lines:
            # Match 01 VARIABLE PIC X(y)
            match = re.match(r'01\s+([A-Z0-9-]+)\s+PIC\s+([^.]*?)(?:\s+VALUE\s+(.*))?\.', line)
            if match:
                var_name = match.group(1).strip().lower().replace('-', '_')
                pic_type = match.group(2).strip()
                default = match.group(3).strip() if match.group(3) else None
                
                rust_type = 'String'
                for pic_key, rust_key in self.rust_types.items():
                    if pic_key in pic_type:
                        rust_type = rust_key
                        break
                
                if default:
                    rust_fields.append(f'    {var_name}: {rust_type} = {default},')
                else:
                    rust_fields.append(f'    {var_name}: {rust_type},')
        
        return '\n'.join(rust_fields)
    
    def translate_procedure(self, procedure_lines):
        """Translate COBOL PROCEDURE DIVISION to Rust function body"""
        rust_code = []
        indent_level = 0
        
        for line in procedure_lines:
            stripped = line.strip()
            upper = stripped.upper()
            
            if 'IF' in upper and 'THEN' in upper:
                condition = upper.replace('IF', '').replace('THEN', '').strip().replace('-', '_')
                rust_code.append(f'{"    " * indent_level}if {condition.lower()} {{')
                indent_level += 1
            elif 'ELSE' in upper:
                indent_level -= 1
                rust_code.append(f'{"    " * indent_level}}} else {{')
                indent_level += 1
            elif 'END-IF' in upper:
                indent_level -= 1
                rust_code.append(f'{"    " * indent_level}}}')
            elif 'COMPUTE' in upper:
                expr = upper.replace('COMPUTE', '').strip()
                expr_clean = expr.lower()
                parts = expr_clean.split('=')
                if len(parts) == 2:
                    var_name = parts[0].strip().replace('-', '_')
                    value = parts[1].strip()  # Keep minus sign for arithmetic
                    rust_code.append(f'{"    " * indent_level}{var_name} = {value};')
                else:
                    rust_code.append(f'{"    " * indent_level}let result = {expr_clean};')
            elif 'MOVE' in upper:
                parts = upper.replace('MOVE', '').split('TO')
                if len(parts) == 2:
                    rust_code.append(f'{"    " * indent_level}let {parts[1].strip().lower().replace(".", "").replace("-", "_")} = {parts[0].strip().lower().replace("-", "_")};')
            elif 'DISPLAY' in upper:
                msg = stripped.replace('DISPLAY', '').strip().strip('"').strip("'")
                rust_code.append(f'{"    " * indent_level}println!("{msg}");')
        
        # Close any remaining open blocks
        while indent_level > 0:
            indent_level -= 1
            rust_code.append(f'{"    " * indent_level}}}')
        
        return '\n'.join(rust_code)
    
    def generate_rust_program(self, divisions):
        """Generate complete Rust program from COBOL divisions"""
        program_id = divisions['IDENTIFICATION'].get('program_id', 'cobol_program').lower().replace('-', '_')
        struct_name = ''.join(word.capitalize() for word in program_id.split('_'))
        
        data_fields = self.translate_data_division(divisions['DATA'].get('working_storage', []))
        procedure_code = self.translate_procedure(divisions['PROCEDURE'])
        
        return f"""// Generated by Gullwing-Tern from COBOL
// Program: {program_id}

#[derive(Debug)]
struct {struct_name} {{
{data_fields}
}}

impl {struct_name} {{
    fn process(&self) {{
{procedure_code}
    }}
}}

fn main() {{
    let app = {struct_name} {{
        // Default values from COBOL WORKING-STORAGE
        customer_balance: 0,
        withdrawal_amount: 0,
        minimum_balance: 500,
    }};
    
    app.process();
}}
"""
